# Generated by Django 2.2.dev20180612192205 on 2019-01-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0002_auto_20190117_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='chapters',
        ),
        migrations.AddField(
            model_name='book',
            name='numChapters',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
